name: minimoonbit

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-basic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: install moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s minimoonbit
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: moon update

      - name: moon check
        run: moon check

      - run: moon test --target all

      - run: moon test --release --target all

      - run: just test-parse

      - run: just test-typecheck

      - run: just test-knf

      - run: just test-closure

      - run: just test-ssa

  build-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: install moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s minimoonbit
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - run: |
          moon update
          moon check

      - name: test js
        run: just test-js

  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: install wasm-tools
        uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-tools

      - name: install moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s minimoonbit
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          wasm-tools --version
          moon version --all
          moonrun --version

      - run: |
          moon update
          moon check

      - name: test wasm
        run: |
          just test-wasm

  build-riscv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: extractions/setup-just@v1

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - uses: actions/cache@v4
        with:
          path: libriscv/emulator/.build/
          key: ${{ runner.os }}-libriscv-emulator
          restore-keys: |
            ${{ runner.os }}-libriscv-emulator
      
      - name: build runtime
        run: |
          ./build_rvlinux.sh
          ./build_riscvrt.sh

      - name: install moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s minimoonbit
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          zig version
          moon version --all
          moonrun --version

      - run: |
          moon update
          moon check

      - name: test riscv
        run: |
          just test-riscv

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s minimoonbit
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: |
          moon update
          moon install

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
